// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmNO2cEzF_ZeWykmAVk9X7nkSYQWCVHfI',
    appId: '1:845986175136:web:d9cc81fb813337da3fd1c5',
    messagingSenderId: '845986175136',
    projectId: 'ghanagermany-cf585',
    authDomain: 'ghanagermany-cf585.firebaseapp.com',
    storageBucket: 'ghanagermany-cf585.firebasestorage.app',
    measurementId: 'G-T7GFPBLDKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzaqiNleksXjtGFW3PpFZQGKdDMLmBPqQ',
    appId: '1:616908782782:android:368e537a9486172a45f2ef',
    messagingSenderId: '616908782782',
    projectId: 'ghana-to-germany',
    storageBucket: 'ghana-to-germany.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1hmTaD13zTP6MSkA8ASkD4WDY8q1jPHE',
    appId: '1:616908782782:ios:576bfeb355d0fc2f45f2ef',
    messagingSenderId: '616908782782',
    projectId: 'ghana-to-germany',
    storageBucket: 'ghana-to-germany.firebasestorage.app',
    iosClientId: '616908782782-l8t2rmv008ufa4r0mobca118hjb49j1b.apps.googleusercontent.com',
    iosBundleId: 'com.devjo.ghanagermany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91FTQebJnSQTVm4Oco9Mnf9AHGg1MLHI',
    appId: '1:845986175136:ios:f47970ed5c650ecd3fd1c5',
    messagingSenderId: '845986175136',
    projectId: 'ghanagermany-cf585',
    storageBucket: 'ghanagermany-cf585.firebasestorage.app',
    iosBundleId: 'com.ghanagermany.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmNO2cEzF_ZeWykmAVk9X7nkSYQWCVHfI',
    appId: '1:845986175136:web:04fd02cd205fc5ce3fd1c5',
    messagingSenderId: '845986175136',
    projectId: 'ghanagermany-cf585',
    authDomain: 'ghanagermany-cf585.firebaseapp.com',
    storageBucket: 'ghanagermany-cf585.firebasestorage.app',
    measurementId: 'G-T0F9BWGBBQ',
  );
}